# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # hier können auch mehrere Versionen angegeben werden
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Run the command to install node deps
      - run: npm ci # bei CI ist ci als Befehl üblich, s. package-lock.json (nutzt node packages zum gegebenen Zeitpunkt)
      # Run the command to start your dev server followed by the & sign
      # Run jest
      - run: npm run serve &
      - run: npm run e2e
      - run: npm run test
